### ISSUE TITLE
Finish tasks before release

### ISSUE THREAD

**Issue by umasagashi** [umasagashi/umacapture#23]
- [x] Add app icon
- [x] Force single instance
- [x] Localization
- [x] Sound notification
- [x] Licenses
- [x] Export
- [x] Add installer
- [x] Updater
- [x] Feedback
- [x] Module downloader
- [x] Re-recongnition
- [x] Add licenses
- [x] Add version
- [x] Change updater domain
