### ISSUE TITLE
Add database management page p2

### ISSUE THREAD

**Issue by umasagashi** [umasagashi/umacapture#45]
- [ ] Add support card spec
- [ ] Add family spec
- [ ] Add scenario record spec
- [ ] Add race history spec
- [ ] Add comment spec
- [ ] Improve CSV export
